##
# This config file is only applicable when building for the FOLIO OKAPI gateway.
# Use the flag '-Denv=okapi'
##

dataSource:
  dbCreate: none
  url: jdbc:postgresql://10.0.2.15:5432/okapi_modules
  username: folio_admin
  password: folio_admin
  driverClassName: org.postgresql.Driver
  dialect: org.hibernate.dialect.PostgreSQLDialect
  schemaHandler: com.k_int.okapi.OkapiSchemaHandler
  properties:
      jmxEnabled: false
      initialSize: 5
      maxActive: 50
      minIdle: 5
      maxIdle: 25
      maxWait: 10000
      maxAge: 600000
      timeBetweenEvictionRunsMillis: 5000
      minEvictableIdleTimeMillis: 60000
      validationQuery: SELECT 1
      validationInterval: 30000
      testOnBorrow: true
      testWhileIdle: true
      testOnReturn: false
      removeAbandoned: true
      removeAbandonedTimeout: 60
      abandonWhenPercentageFull: 50
      jdbcInterceptors: ConnectionState
      defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
      
      